server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/handicrafts_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sohail@786
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=TribalHandicraftsPlatformSecretKeyForJwtTokenAtLeast32Chars
jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hardikmittal2908@gmail.com
spring.mail.password=aceeyozcjdckuchc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.banner-mode=off
logging.pattern.console=%d{HH:mm:ss} - %msg%n
logging.level.root=WARN
logging.level.com.backend.handicrafts=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
